// 首页壁纸
export const Cover = [
    "/cover/bg01.webp",
    "/cover/bg02.webp",
    "/cover/bg03.webp",
    "/cover/bg04.webp",
    "/cover/bg05.webp",
    "/cover/bg06.webp",
    "/cover/bg07.webp",
    "/cover/bg08.webp",
    "/cover/bg09.webp",
    "/cover/bg10.webp",
    "/cover/bg11.webp",
    "/cover/bg12.webp",
    "/cover/bg13.webp",
    "/cover/bg14.webp",
    "/cover/bg15.webp",
    "/cover/bg16.webp",
    "/cover/bg17.webp",
    "/cover/bg18.webp",
    "/cover/bg19.webp",
    "/cover/bg20.webp",
    "/cover/ly01.jpg",
    "/cover/ly03.png",
    "/cover/ly04.jpg",
    "/cover/ly05.jpg",
];
